### PR TITLE
V4

### LINKED ISSUE #9: Add contributors to package.json

### LINKED ISSUE #10: Improve docs
- [ ] Returns a `bool`. -> Boolean?
- [ ] t: Number - lerp value -> ratio between v and w
- [ ] lerped -> interpolated
- [ ] Number vs number
- [ ] squared length -> square length? (need to google that)

### LINKED ISSUE #14: Implement quat.targetTo
This is too useful to not have it. Especially with the new pex-renderer where everything depends on transform (lights, camera, geometries) and it's hard to rotate meshes with Euler angles.

### LINKED ISSUE #16: Update quat.fromTo docs
The `up` param is not used.

In response to https://github.com/pex-gl/pex-math/issues/15

### LINKED ISSUE #25: Consider adding TOC to docs
```
|vec2|vec3|vec3|
|----|----|----|
|[add](#vec2addv-w)|add|add|
|n/a|normalize|n/a|
```

Screenshot 2019-04-25 at 12 14 19

### LINKED ISSUE #26: quat.fromTo should check for negligible values
Both Three.js and gl-matrix implementation check the dot product for Number.EPSILON or 0.000001.

https://github.com/toji/gl-matrix/blob/fccd5f707432ec5cc1774575be84c9f901a198d0/src/quat.js#L699-L727

https://github.com/mrdoob/three.js/blob/d4aa9e00ea29808534a3e082f602c544e5f2419c/src/math/Quaternion.js#L363-L404

### LINKED ISSUE #30: Remove fromTo
Replace with `fromDirection(dir, up)`

### LINKED ISSUE #31: Remove targetTo

### PR DESCRIPTION
**Pull request by dmnsgn**
Changes:

- [x] refactor: convert to esm
- [x] feat: export \_fromMat39 in quat
- [x] refactor: replace mat3 let with const
- [x] refactor: replace mat4 \_rotate3 let with const
- [x] perf: remove assert (performance gain)
- [x] refactor: remove 1.0 and 0.0
- [x] feat: add EPSILON
- [x] perf: replace slice(0) with slice()
- [x] perf: _rotate3 has useless multiplication by zero
- [x] refactor: mat4.\_lookAt9 is duplicate of mat4.lookAt
- [x] refactor: mat4._lookAt9 return identity if < epsilon
- [x] perf: mat4._lookAt9 has early let declarations
- [x] perf: divide by 2
- [x] refactor: reorder functions
- [x] docs: auto-generate
- [x] test: add all mat4 methods to bemchmark
- [x] perf: mat4 mult / invert caching
- [x] perf: inline mat4.fromTranslationRotationScale
- [x] refactor: prevent duplicate copy and vec4 methods

To test:

- [x] perf: ~~use Math.hypot (quat.length, vec2/3.length, vec2/3.distance)~~
- [x] perf: ~~/ 2 or \* 0.5 ? (quat.fromEuler)~~
- [x] perf: ~~copy~~
- [x] test: quat benchmarks
- [x] perf: quat.fromTo wrapped function

Implementation:

- [x] quat.normalize epsilon is 2 \*\* -24
- [x] mat4.\_lookAt9 doesn't check for len === 0 (https://github.com/toji/gl-matrix/blob/0bca31acb13cdaa6eaa2bd615b053d9fdd4e7b72/src/mat4.js#L1773)
- [x] quat.fromAxisAngle is missing epsilon check (https://github.com/toji/gl-matrix/blob/0bca31acb13cdaa6eaa2bd615b053d9fdd4e7b72/src/quat.js#L73)

TBD:

- [x] use new Float32Array by default
- [x] rename _methods (_set9(), _rotate3, _lookAt9)
- [x] implement quat.targetTo
- [x] remove toString

Closes #9 
Closes #10 
Closes #14 
Closes #16 
Closes #25 
Closes #26 
Closes #30 
Closes #31

### CODE REVIEW

**Comment by vorg** [comment]
Thanks for the work so far. Yes let's discuss TBD items one by one below.

**Comment by dmnsgn** [comment]
> use new Float32Array by default

Benchmark lean towards keeping array

**Comment by dmnsgn** [comment]
> remove toString

@vorg do you ever use it/think it is needed?

**Comment by vorg** [comment]
@dmnsgn I use `toString` when i remember it exists... usually i would do
```javascript
`[${vec.map((f) => f.toFixed(2)).join(', ')}]`
```

**Comment by vorg** [comment]
@dmnsgn I use `toString` when i remember it exists... usually i would do
```javascript
`[${vec.map((f) => f.toFixed(2)).join(', ')}]`
```

**Comment by dmnsgn** [comment]
So you think we should remove it or simplify it to use map + toFixed?

**Comment by vorg** [comment]
Yes, i'm ok with it.

**Comment by vorg** [comment]
If PR is not merged until ready how one published beta version on npm?

**Comment by dmnsgn** [comment]
Ideally but not what you want (see below):
`npx snowdev release --prerelease alpha` (if you want to see what would happen, you can test it with `npx snowdev release --prerelease alpha --dry-run`)

One issue with pex-math is that package currently shows 3.0.0-4, so the above will result in `v3.0.0-alpha.0` instead of `v4.0.0-alpha.0`. So you'd need to do:
- `npx snowdev release --prerelease 4.0.0-alpha.0`
- `npm publish --tag 4.0.0-alpha.0` or `npm publish --tag alpha`

**Comment by vorg** [comment]
Ok thanks. Is `3.0.0-4` < `v3.0.0-alpha.0` ? If yes then we could still stick with v3.0 as it was never released?

**Comment by vorg** [comment]
Well it's been 2y. v4 it is.

**Comment by vorg** [comment]
snowdev gives me 

> Cannot parse the config file /Users/vorg/.npm/_npx/9b4e921c3008582b/node_modules/snowdev/jsdoc.json: Error: ENOENT: no such file or directory, open '/Users/vorg/.npm/_npx/9b4e921c3008582b/node_modules/snowdev/jsdoc.json'

**Comment by dmnsgn** [comment]
@vorg can you try with `snowdev@1.10.4` ?

**Comment by vorg** [comment]
Quick snowdev release info for alpha versions

```sh
# autoincrement version (patch, minor, major if breaking change)
npx snowdev release --prerelease alpha

# specify which sem ver to bump
npx snowdev release --release-as minor --prerelease alpha
```

Continues calls to `--prerelease alpha` will keep adding `.0`, `.1`, `.2` etc to full `3.0.0-alpha.2` version

**Comment by vorg** [comment]
- [x] keep copy functions
- [x] keep parameter names (s, t)
- [x] remove mat4._lookAt, mat4._rotate3, mat4._scale3, mat4._translate3
- [ ] remove quat. _fromMat39
- [x] remove new vec4/avec4 functions 
- [x] add (a)vec4.lerp
- [x] please no, `export const normalize = vec4.normalize;`

**Comment by dmnsgn** [comment]
Have to keep quat._fromMat39 as it is used in 3 independent places internally. Any suggestion on renaming it @vorg ?

**Comment by vorg** [comment]
@dmnsgn not really as it is mat3 with 9 parameters.

**Comment by dmnsgn** [comment]
- [x] add avec3.multMat4
- [x] add avec3.multQuat

**Comment by dmnsgn** [comment]
Should we default `avec` j parameter to 0 if it is last in arguments list?
```diff
+ export function add(a, i, b, j = 0) {
- export function add(a, i, b, j) {
  a[i * 3] += b[j * 3];
  a[i * 3 + 1] += b[j * 3 + 1];
  a[i * 3 + 2] += b[j * 3 + 2];
}
```

This would help when transforming an avec by a regular vec3 eg.:
```js
import { avec3 } from "pex-math";
const myVec3 = [1,0,0];
const myGeom = plane();

for (let i = 0; i < myGeom.positions.length /3; i++) {
  avec3.add(myGeom.positions, i, myVec3);
  // instead of avec3.add(myGeom.positions, i, myVec3, 0);
}
```

**Comment by vorg** [comment]
I would say no defaults. I like to see the 0

**Pull request merged**
