### PR TITLE
Add mat2d, mat3.fromMat2d and mat4.fromTranslationRotationScale

### LINKED ISSUE #20: Add mat3.fromTranslationRotationScale
Wondering if this should also be part of the pex-math or not (used in pex-renderer to get a matrix from texture transform):
```js
function fromTranslationRotationScale(translation, rotation, scale) {
  const c = Math.cos(rotation)
  const s = Math.sin(rotation)

  return mat3.mult(
    mat3.mult(
      [
        1, 0, 0,
        0, 1, 0,
        translation[0], translation[1], 1
      ],
      [
        c, s, 0,
        -s, c, 0,
        0, 0, 1
      ]
    ),
    [
      scale[0], 0, 0,
      0, scale[1], 0,
      0, 0, 1
    ]
  );
}
```

cc @vorg

### PR DESCRIPTION
**Pull request by dmnsgn**
- Add mat2d (pex-renderer texture transform)
- Add mat3.fromMat2d (pex-renderer texture transform)
- Add mat4.fromTranslationRotationScale (pex-renderer transform component localModelMatrix)

Fix #20

### CODE REVIEW

**Comment by vorg** [comment]
Most rotations in pex-renderer are Quaternions. In pex-math we do have old OpenGL axis + angle rotations too. What's the use case for `mat3.fromTranslationRotationScale(t, s, r)`? What's the axis of the rotation? 

Mat3 is capable of representing 3d rotations and `mat3.fromQuat` exists so we could align with `mat4` and accept `quat` in both cases. Currently in this PR it's confusing to have 2 functions with the same name but different types.

**Comment by dmnsgn** [comment]
I updated the first comment with usage.
mat2d should be faster for texture transform as offset and scale are `array[2]`  and rotation is in radians.
I removed `mat3.fromTranslationRotationScale` as it will be confusing and not needed anymore with the addition of mat2d.

**Comment by vorg** [comment]
1. How is it faster? Because we don't use quaternions for such a simple rotation?
2. I think `mat23` is a better name because we don't have `mat3d`
3. Here is a crazy idea. From the [KHR_texture_transform specs](https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_texture_transform#overview).

> This is equivalent to Unity's Material#SetTextureOffset and Material#SetTextureScale, or Three.js's Texture#offset and Texture#repeat. UV rotation is not widely supported as of today, but is included here for forward compatibility.

I can't think of an use case where texture rotation would be useful. That simplifies data to vec2 offset and vec2 scale which... can be sent together as one vec4 and no need for mat23. Hmm?

**Comment by dmnsgn** [comment]
> 1. How is it faster? Because we don't use quaternions for such a simple rotation?

And because it is 6 and not 9 elements

> 2. I think `mat23` is a better name because we don't have `mat3d`

I took it from glmatrix. What about `mat2x3` instead to match OpenGL and WebGL 2?

> 3. Here is a crazy idea. From the [KHR_texture_transform specs](https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_texture_transform#overview).
> 
> > This is equivalent to Unity's Material#SetTextureOffset and Material#SetTextureScale, or Three.js's Texture#offset and Texture#repeat. UV rotation is not widely supported as of today, but is included here for forward compatibility.
> 
> I can't think of an use case where texture rotation would be useful. That simplifies data to vec2 offset and vec2 scale which... can be sent together as one vec4 and no need for mat23. Hmm?

Imagine an atlas of 4 rectangular textures 300x130:
```
Altlas: 512x512

Columns layout:
- 300 + [82] + 130
- 300 + [82] + 130
- 300 + [212]

Row layout:
130 +
130 +
130 +
[122]
___________
| / / /  / |
| / / /  / | 
| / / /    | 
___________
```

**Review by vorg — APPROVED** [review]
Since there is `mat2x3` in webgl2 then awesome and all good to go!

**Comment by dmnsgn** [comment]
Cool, I updated yesterday, it's ready to be merged.

**Comment by vorg** [comment]
Published as `pex-math@next` aka `pex-math@3.0.0-2`

**Pull request merged**
